### ISSUE TITLE
Compile with Intel Compiler 2018.2.199 - math.h(1230): error: identifier "_LIB_VERSION_TYPE" is undefined

### ISSUE THREAD

**Issue by codewerfer** [gismo/gismo#255]
There is a bug with *Intel Compiler 2018.2.199* on some Linux machines.

At the moment we are working to fix this.
Some suggestions:
* [ ] add `-D__PURE_INTEL_C99_HEADERS__` to `CMAKE_CXX_FLAGS`
* [ ] GCC 8.2.0
* [ ] force to GCC 6.4.0 `-gxx-name=/usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/g++ -gcc-name=/usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/gcc`
